version: "3.5"

services:
  kdb:
    image: mysql
    container_name: kdb
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password  
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: keiron
    restart: always
    tty: true
  
  kapi:
    image: knode:12.2.0
    container_name: kp
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          memory: 512MB
        reservations:
          memory: 512MB
    build:
      context: ./api 
      dockerfile: ./dockerfile
    depends_on:
      - kdb
    ports:
      - "8686:8000"
    links:
      - kdb
    volumes:
      - "./api:/api"  
      - "/api/node_modules"  
    tty: true  


  client:
    image: knode:12.2.0-alpine
    container_name: kc
    restart: always
    deploy:
      resources:
        limits:
          memory: 4024MB
        reservations:
          memory: 4024MB
    environment:
      NODE_ENV: development
    stdin_open: true  
    ports:
      - "4444:3000"
    build:
      context: ./client
      dockerfile: ./dockerfile
    volumes:
      - "./client:/client"    
      - "/client/node_modules"    
    links:
      - kapi
    depends_on:
      - kapi  
    tty: true  
    
